name       : f3
version    : 7.1
release    : 1
source     :
    - https://github.com/AltraMayor/f3/archive/v7.1.tar.gz : 1d9edf12d3f40c03a552dfc3ed36371c62933b9213483182f7a561e1a5b8e1cc
license    : GPL-3.0
component  : system.utils
summary    : Fight Flash Fraud / Fight Fake Flash
description: |
    A fake flash drive fraudulently inflates its apparent storage capacity (far) beyond the physical capacity of its flash memory. Not surprisingly, using such a flash drive will, sooner or later, result in data loss and/or corruption.

    The main tools in this package are an open-source implementation of the H2testw algorithm. Some extra tools are also provided, among them one for using the actual storage capacity of fake drives as safely as possible.
builddeps  :
    - pkgconfig(libparted)
build      : |
    %make extra
install    : |
    %make_install PREFIX=/usr
    %make install-extra DESTDIR=$installdir PREFIX=/usr