name       : f3
version    : '7.2'
release    : 2
source     :
    - https://github.com/AltraMayor/f3/archive/v7.2.tar.gz : ba9210a0fc3a42c2595fe19bf13b8114bb089c4f274b4813c8f525a695467f64
homepage   : https://github.com/AltraMayor/f3
license    : GPL-3.0-or-later
component  : system.utils
summary    : Fight Flash Fraud / Fight Fake Flash
description: |
    A fake flash drive fraudulently inflates its apparent storage capacity (far) beyond the physical capacity of its flash memory. Not surprisingly, using such a flash drive will, sooner or later, result in data loss and/or corruption. The main tools in this package are an open-source implementation of the H2testw algorithm. Some extra tools are also provided, among them one for using the actual storage capacity of fake drives as safely as possible.
builddeps  :
    - pkgconfig(libparted)
build      : |
    %make extra
install    : |
    %make_install PREFIX=/usr
    %make install-extra DESTDIR=$installdir PREFIX=/usr
