name       : f3
version    : '8.0'
release    : 4
source     :
    - https://github.com/AltraMayor/f3/archive/v8.0.tar.gz : fb5e0f3b0e0b0bff2089a4ea6af53278804dfe0b87992499131445732e311ab4
homepage   : https://github.com/AltraMayor/f3
license    : GPL-3.0-or-later
component  : system.utils
summary    : Fight Flash Fraud / Fight Fake Flash
description: |
    A fake flash drive fraudulently inflates its apparent storage capacity (far) beyond the physical capacity of its flash memory. Not surprisingly, using such a flash drive will, sooner or later, result in data loss and/or corruption. The main tools in this package are an open-source implementation of the H2testw algorithm. Some extra tools are also provided, among them one for using the actual storage capacity of fake drives as safely as possible.
builddeps  :
    - pkgconfig(libparted)
build      : |
    %make extra
install    : |
    %make_install PREFIX=/usr
    %make install-extra DESTDIR=$installdir PREFIX=/usr
